### ISSUE TITLE
TODO for IOT Project

### ISSUE THREAD

**Issue by SridharPandian** [SridharPandian/Drone-Delivery#2]
Checklist:
- [x] Drone Chassis
- [x] Connecting with Raspi
- [x] Elevation motor code
- [ ] Controlled Elevation and descent
- [ ] Directional control
- [ ] Drone Location Tracking
- [ ] Navigation to coordinates ( CLI )
- [ ] Camera integration and face recognition
- [ ] Way to attach object holder
- [ ] Arduino lock/unlock of package
- [ ] Security testing

- [ ] AWS IOT Pi connect
- [ ] AWS Lambda backend implementation
- [ ] Frontend implementation with input location and facial data
